/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;
import Crucigramas.GridField;
import Crucigramas.Word;
import Crucigramas.WordList;//talvez no sea necesatrio
import FileManager.ReaderManager;
import FileManager.WriterManager;
import java.awt.GridLayout;
import java.io.*;
import Game.Main;
import java.awt.LayoutManager;
import javafx.scene.control.TextField;
/**
 *
 * @author usuario
 */


public class Crossword extends javax.swing.JDialog {
    //una prueba de referencia a reader
ReaderManager readerTxt = new ReaderManager();
WriterManager writerTxt = new WriterManager();
    /**
     * Creates new form Easy
     * constructor easy modificado con jaavax.swing
     */
    public Crossword(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);        
        initPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btBack = new javax.swing.JButton();
        btTesting = new javax.swing.JButton();
        btClue = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        jpCross = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btBack.setText("Atras");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        btTesting.setText("Comprobar");
        btTesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTestingActionPerformed(evt);
            }
        });

        btClue.setText("?");

        lbTitulo.setText("Nivel Fácil");

        jpCross.setBackground(new java.awt.Color(153, 51, 255));
        jpCross.setMinimumSize(new java.awt.Dimension(300, 150));
        jpCross.setPreferredSize(new java.awt.Dimension(250, 150));

        javax.swing.GroupLayout jpCrossLayout = new javax.swing.GroupLayout(jpCross);
        jpCross.setLayout(jpCrossLayout);
        jpCrossLayout.setHorizontalGroup(
            jpCrossLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpCrossLayout.setVerticalGroup(
            jpCrossLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btClue)
                .addGap(106, 106, 106)
                .addComponent(lbTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btTesting)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jpCross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClue)
                    .addComponent(lbTitulo))
                .addGap(4, 4, 4)
                .addComponent(jpCross, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBack)
                    .addComponent(btTesting))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        dispose();
    }//GEN-LAST:event_btBackActionPerformed
    ///private void 
    private void btTestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTestingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTestingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btClue;
    private javax.swing.JButton btTesting;
    private javax.swing.JPanel jpCross;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
    
    
    /**
     * metodo  generador dinamico de matrices
     * @return no retorna
     * @param sin parametros
     */
    
    private void initPanel() {
        //Main.WORD_MANAGER.getWord(1);
        int cols = 5;
        int rows = 6;
        
        GridLayout gridLayout = new GridLayout(rows, cols);
        //panelGlayout.setLayout(grid);//esto lo substituye el gridLayout??

            for (int f = 0; f < rows; f++) {
                for (int j = 0; j < cols; j++) {
                     GridField newTextField = new GridField(f,j,1,1);
                    jpCross.setLayout(gridLayout);
                    jpCross.add(newTextField);
                    //gridLayout.addLayoutComponent("asd", newTextField);
                    
                }
            }
            
            //
 //           newGridField.addActionListener(new java.awt.event.ActionListener() {
//                public void actionPerformed(java.awt.event.ActionEvent evt) {
//                    if (evt.getSource() == newGridField) {
////                        product = newGridButtom.getProduct();
////                        Icon icon = new ImageIcon(getClass().getResource(
////                                "/img/" + product.getImageName()));
////                        lbImage.setIcon(icon);
//                    }
//                }
//            });
    }
    
    
//     /**
//      * metodo para leer palaras
//      * @param sin parametros
//      * @return no retorna
//      */
//    private void readWords(){
//            
//        //ReaderManager readerTxt = new ReaderManager();
//        try {
//            readerTxt.open("CrossWordFiles/Easy/1.txt");
//            //
//            System.out.println(readerTxt.read());//creo que aqui va un while + arraycopy
//            System.out.println(readerTxt.read());
//            System.out.println(readerTxt.read());
//            System.out.println(readerTxt.read());
//            //
//            readerTxt.close(); //importante cerrar el archivo
//            System.out.println("Lectura exitosa de texto en reader");
//        } catch (IOException ex) {
//            System.err.println("error de archivo texto en reader");
//            System.err.println(ex.getMessage());
//            //ex.printStackTrace();
//        }
//    }
//    /**
//     * metodo para añadir palabras no retorna
//     */
//    public void writeWords(){
//            Word matrSize=new Word(5, 5);
//            Word w1=new Word(0,0, 0, "V", "la palabrea", "la descripcion");
//            Word w2=new Word(0,1,1,"V","otraPalabra","suDescipcion");
//            Main.WORD_MANAGER.addWord(matrSize);
//            Main.WORD_MANAGER.addWord(w1);
//            Main.WORD_MANAGER.addWord(w2);
//            //
//            System.out.println("counterWord="+Main.WORD_MANAGER.getLength());
//            System.out.println(Main.WORD_MANAGER.getListString());
//            //
//            
//        try {
//            writerTxt.open("CrossWordFiles/Easy/1.txt");  //probar el parametro apend en new FileWriter(fileName, true)
//            writerTxt.writeAll();
//            writerTxt.close(); //importante cerrar el archivo 
//            System.out.println("Escritura exitosa texto en writer");
//        } catch (IOException ex) {
//            System.err.println("error de archivo texto en writer");
//            System.err.println(ex.getMessage());
//            //ex.printStackTrace();
//        }
//    
//    
//    
//    }
}
