/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;
import Crucigramas.Word;
import FileManager.ReaderManager;
import FileManager.WriterManager;
import java.awt.GridLayout;
import java.io.*;
import Game.Main;
/**
 *
 * @author usuario
 */


public class Easy extends javax.swing.JDialog {

    /**
     * Creates new form Easy
     * constructor easy modificado con jaavax.swing
     */
    public Easy(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btBack = new javax.swing.JButton();
        btTesting = new javax.swing.JButton();
        btClue = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        panelGLayout = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btBack.setText("Atras");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        btTesting.setText("Comprobar");
        btTesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTestingActionPerformed(evt);
            }
        });

        btClue.setText("?");

        lbTitulo.setText("Nivel Fácil");

        panelGLayout.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btClue)
                        .addGap(79, 79, 79)
                        .addComponent(lbTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btTesting)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(panelGLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClue)
                    .addComponent(lbTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBack)
                    .addComponent(btTesting))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        dispose();
    }//GEN-LAST:event_btBackActionPerformed
    ///private void 
    private void btTestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTestingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTestingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btClue;
    private javax.swing.JButton btTesting;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelGLayout;
    // End of variables declaration//GEN-END:variables
    
    /**
     * metodo  generador dinamico de matrices
     * @return no retorna
     * @param sin parametros
     */
//    private void initPanel() {
//        int cols = 2;
//        int rows = (dishList.getProductCounter() % 2 == 0)
//                ? dishList.getProductCounter() % 2
//                : dishList.getProductCounter() % 2 + 1;
//        GridLayout grid = new GridLayout(rows, cols);
//        //panelGlayout.setLayout(grid);//esto lo substituye el gridLayout??
//
//        for (int i = 0; i < dishList.getProductCounter(); i++) {
//            GridButtom newGridButtom = new GridButtom(dishList.getProduct(i));
//            pnDishes.add(newGridButtom);
//            newGridButtom.addActionListener(new java.awt.event.ActionListener() {
//                public void actionPerformed(java.awt.event.ActionEvent evt) {
//                    if (evt.getSource() == newGridButtom) {
//                        product = newGridButtom.getProduct();
//                        Icon icon = new ImageIcon(getClass().getResource(
//                                "/img/" + product.getImageName()));
//                        lbImage.setIcon(icon);
//                    }
//                }
//            });
//        }
//    }
    ////
        ////
        ///prueba de lectura escritura de TEXT
        ////
    
    private void ReaderWriter(){
        Word w1=new Word(0, 0, 0, "V", "la palabrea", "la descripcion");
        
        Main.WORD_MANAGER.addWord(w1);
        
      
        System.out.println("counterWord="+Main.WORD_MANAGER.getLength());
        System.out.println(Main.WORD_MANAGER.getListString());
            
        ReaderManager readerTxt = new ReaderManager();
        try {
            readerTxt.open("CrossWordFiles/Easy/1.txt");
            System.out.println(readerTxt.read());//creo que aqui va un while + arraycopy
            System.out.println(readerTxt.read());
            System.out.println(readerTxt.read());
            System.out.println(readerTxt.read());
            readerTxt.close(); //importante cerrar el archivo
            System.out.println("Lectura exitosa de texto en reader");
        } catch (IOException ex) {
            System.err.println("error de archivo texto en reader");
            System.err.println(ex.getMessage());
            //ex.printStackTrace();
        }

        WriterManager writerTxt = new WriterManager();
        try {
            writerTxt.open("CrossWordFiles/Easy/1.txt");  //probar el parametro apend en new FileWriter(fileName, true)
            writerTxt.writeAll();
            writerTxt.close(); //importante cerrar el archivo 
            System.out.println("Escritura exitosa texto en writer");
        } catch (IOException ex) {
            System.err.println("error de archivo texto en writer");
            System.err.println(ex.getMessage());
            //ex.printStackTrace();
        }
    }
}
